### ISSUE TITLE
Upload Model?

### ISSUE THREAD

**Issue by yradwan147** [khazit/Lip2Word#1]
Hey! I really am interested in your code and was wondering if you could upload your pretrained model so that I can run some tests on it. My computer isn't really strong enough to train it from scratch. 
Hoping for a quick reply,

**Comment by khazit** [comment]
Hi ! Of course, just leave me you email and I'll send you the download link. Send me a message on Twitter if you don't want to leave you email adress in a public issue.

**Comment by yradwan147** [comment]
Sure right here : yradwan147.yr@gmail.com

**Comment by naveen333nav** [comment]
Hello... Could you please send me the link too..
Thanks in advance ..

**Comment by naveen333nav** [comment]
I didn't have any such highend hardware specs(like GTX 1080 Ti  ) and the  dataset (nearly 50-60 GB) needs permission of BBC .

**Comment by PoojaAsati** [comment]
Hi, Can you please share the link of pretrained model? I am really interested in your code but my laptop computation ability is low to train it from scratch. My email id is prarambh06@gmail.com. Thanks in advance!
