### ISSUE TITLE
Request for pretraine model.. 

### ISSUE THREAD

**Issue by naveen333nav** [khazit/Lip2Word#2]
Could you please send me link for downloading model.. I'm lack of dataset as well as hardware requirements (though I can use Google Colab but i don't know how to load such large dataset into Colab for training)

**Comment by khazit** [comment]
Done, check you email

**Comment by chahatagarwal** [comment]
Hey, I have DM'ed you in twitter. Could you please share the pre-trained weights to my mailbox? Thanks.
